spring:
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: user-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true # sql 로깅
        format_sql: true # SQL 문 정렬하여 출력
        highlight_sql: true # SQL 문 색 부여
  #        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시

  redis:
    data:
      host: localhost
      port: 6379

server:
  port: 19092


logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

google:
  map:
    key: AIzaSyA43sMl6VkhJEWoLv_qv6PpDnoU8RGv2aY

springdoc:
  api-docs:
    enabled: true
    path: /user-service/v3/api-docs
  swagger-ui:
    path: /user-service/swagger-ui.html

